In [18]:
import pandas as pd
import numpy as np


In [39]:
np.set_printoptions(formatter={'float': '{: 6.2f}'.format})
df2016 = np.genfromtxt('AAPL-2016.csv', delimiter=',', skip_header = 1)
df2017 = np.genfromtxt('AAPL-2017.csv', delimiter=',', skip_header = 1)
t_df2016 = np.delete(df2016, (0), axis=1)
print(t_df2016)

[[ 102.61  105.37  102.00  105.35  100.27  67649400.00]
 [ 105.75  105.85  102.41  102.71  97.76  55791000.00]
 [ 100.56  102.37  99.87  100.70  95.85  68457400.00]
 ...
 [ 115.59  116.52  115.59  116.52  113.37  14249500.00]
 [ 116.52  117.80  116.49  117.26  114.09  18296900.00]
 [ 117.52  118.02  116.20  116.76  113.61  20905900.00]]


In [22]:
print("shape of 2016",df2016.shape)
print("shape of 2017",df2017.shape)

shape of 2016 (250, 7)
shape of 2017 (251, 7)


In [14]:
df2017.sum(axis=0)

array([           nan, 3.77616700e+04, 3.80029200e+04, 3.75214001e+04,
       3.77883199e+04, 3.71010567e+04, 6.81042620e+09])

In [32]:
empty_array = []
for each_column in df2017:
    empty_array.append(each_column[1:])

t_df2017 = np.asarray(empty_array)
print(t_df2017)

[[ 115.80  116.33  114.76  116.15  113.01  28781900.00]
 [ 115.85  116.51  115.75  116.02  112.89  21118100.00]
 [ 115.92  116.86  115.81  116.61  113.46  22193600.00]
 ...
 [ 170.10  170.78  169.71  170.60  168.66  21498200.00]
 [ 171.00  171.85  170.48  171.08  169.14  16480200.00]
 [ 170.52  170.59  169.22  169.23  167.31  25884400.00]]


In [29]:
df2017.sum(axis=0)

array([   nan,  37761.67,  38002.92,  37521.40,  37788.32,  37101.06,
        6810426200.00])