In [1]:
import pandas as pd
import numpy as np


In [2]:
np.set_printoptions(formatter={'float': '{: 6.2f}'.format})
df2016 = np.genfromtxt('AAPL-2016.csv', delimiter=',', skip_header = 1)
df2017 = np.genfromtxt('AAPL-2017.csv', delimiter=',', skip_header = 1)
t_df2016 = np.delete(df2016, (0), axis=1)
print(t_df2016)

[[ 102.61  105.37  102.00  105.35  100.27  67649400.00]
 [ 105.75  105.85  102.41  102.71  97.76  55791000.00]
 [ 100.56  102.37  99.87  100.70  95.85  68457400.00]
 ...
 [ 115.59  116.52  115.59  116.52  113.37  14249500.00]
 [ 116.52  117.80  116.49  117.26  114.09  18296900.00]
 [ 117.52  118.02  116.20  116.76  113.61  20905900.00]]


In [3]:
print("shape of 2016",df2016.shape)
print("shape of 2017",df2017.shape)

shape of 2016 (250, 7)
shape of 2017 (251, 7)


In [5]:
t_df2016.sum(axis=0)

array([ 26102.86,  26333.34,  25898.12,  26127.66,  25175.42,
        9634995700.00])

In [8]:
empty_array = []
for each_column in df2017:
    empty_array.append(each_column[1:])

t_df2017 = np.asarray(empty_array)
print(t_df2017)

[[ 115.80  116.33  114.76  116.15  113.01  28781900.00]
 [ 115.85  116.51  115.75  116.02  112.89  21118100.00]
 [ 115.92  116.86  115.81  116.61  113.46  22193600.00]
 ...
 [ 170.10  170.78  169.71  170.60  168.66  21498200.00]
 [ 171.00  171.85  170.48  171.08  169.14  16480200.00]
 [ 170.52  170.59  169.22  169.23  167.31  25884400.00]]


In [9]:
t_df2017.sum(axis=0)

array([ 37761.67,  38002.92,  37521.40,  37788.32,  37101.06,
        6810426200.00])

In [11]:
conda install numpy

ValueError: operands could not be broadcast together with shapes (251,6) (250,6) 

In [12]:
print("shape of 2016",t_df2016.shape)
print("shape of 2017",t_df2017.shape)

shape of 2016 (250, 6)
shape of 2017 (251, 6)


In [13]:
tt_df2017 = t_df2017[0:-1]

In [14]:
print(tt_df2017.shape)

(250, 6)


In [17]:
tt_df2017.sum(axis=0) - t_df2016.sum(axis=0)

array([ 11488.29,  11498.99,  11454.06,  11491.43,  11758.32,
        2850453900.00])

In [19]:
print(tt_df2017)
print('**')
print(t_df2016)

[[ 115.80  116.33  114.76  116.15  113.01  28781900.00]
 [ 115.85  116.51  115.75  116.02  112.89  21118100.00]
 [ 115.92  116.86  115.81  116.61  113.46  22193600.00]
 ...
 [ 170.80  171.47  169.68  170.57  168.63  33185500.00]
 [ 170.10  170.78  169.71  170.60  168.66  21498200.00]
 [ 171.00  171.85  170.48  171.08  169.14  16480200.00]]
**
[[ 102.61  105.37  102.00  105.35  100.27  67649400.00]
 [ 105.75  105.85  102.41  102.71  97.76  55791000.00]
 [ 100.56  102.37  99.87  100.70  95.85  68457400.00]
 ...
 [ 115.59  116.52  115.59  116.52  113.37  14249500.00]
 [ 116.52  117.80  116.49  117.26  114.09  18296900.00]
 [ 117.52  118.02  116.20  116.76  113.61  20905900.00]]


In [23]:
change = tt_df2017 - t_df2016
print(change)

[[ 13.19  10.96  12.76  10.80  12.74 -38867500.00]
 [ 10.10  10.66  13.34  13.31  15.13 -34672900.00]
 [ 15.36  14.49  15.94  15.91  17.61 -46263800.00]
 ...
 [ 55.21  54.95  54.09  54.05  55.26  18936000.00]
 [ 53.58  52.98  53.22  53.34  54.57  3201300.00]
 [ 53.48  53.83  54.28  54.32  55.53 -4425700.00]]


In [25]:
sum_diff = change.sum(axis=0)
print(sum_diff)

[ 11488.29  11498.99  11454.06  11491.43  11758.32 -2850453900.00]


In [27]:
sum_diff_volume = sum_diff[5]
print(sum_diff_volume)

-2850453900.0


In [72]:
combined_years = np.append(t_df2016,tt_df2017, 0)

In [73]:
len(combined_years)

250

In [71]:
print(combined_years)

[[ 102.61  105.37  102.00  105.35  100.27  67649400.00]
 [ 105.75  105.85  102.41  102.71  97.76  55791000.00]
 [ 100.56  102.37  99.87  100.70  95.85  68457400.00]
 ...
 [ 170.80  171.47  169.68  170.57  168.63  33185500.00]
 [ 170.10  170.78  169.71  170.60  168.66  21498200.00]
 [ 171.00  171.85  170.48  171.08  169.14  16480200.00]]
